currency:
  # Use the specified currency below over Vault if Vault is enabled
  override-vault: false
  # accepts a material or a placeholder
  # if the currency is a material, the plugin will automatically take away the necessary amounts
  object: 'DIAMOND'
  # before the currency in all occurrences in language.yml
  prefix: '&f'
  suffix: '&b◆'
  # only needed if you are using a placeholder, but will be called either way.
  # {player} & {amount} or use a placeholder
  remove-commands: [] # ['eco take {player} {amount}']
  add-commands: [] # ['eco give {player} {amount}']
  # if you are using multiple currencies
  # descending - currency will be given in descending order of weights
  # first - only the first currency in the object list will be given
  # ratio - a ratio of the currencies with their weights will be given
  add-single-currency: descending
# formatting of large numbers
number-formatting:
  # Same as EssentialsX config
  # For 1.234,50 use de-DE
  # For 1,234.50 use en-US
  # For 1'234,50 use fr-ch
  format-locale: en-US
  # pattern for currency to be displayed - symbols are only placeholders, if you want to change the symbols, change format-locale
  pattern: '#,###.##'
  use-divisions: true
  # makes the number smaller and adds a suffix ex: 1000 = 1K | 1234 = 1.23K | 5467900 = 5.47M
  divisions:
    # the division and suffix
    1000: K
    1000000: M
    1000000000: B
    1000000000000: T
# minimum amount of currency a bounty can be
minimum-bounty: 1
# minimum amount of currency that will broadcast bounties
minimum-broadcast: 50
# percent extra they have to pay to set a bounty - uses a DECIMAL
# ex: bounty-tax = 0.25, a bounty set for 100 would cost 125 to be placed
# use this if players are setting too many bounties
bounty-tax: 0.0
# same as bounty-tax, except the player who dies has to pay this
# ex: death-tax = 0.1, a bounty set for 100 would cost the player 10 when they die
# players cannot go into debt
death-tax: 0.0
# how many real days until bounties expire
bounty-expire: -1
# These player's bounty stats will be hidden from bounties top
hide-stats:
  - Not_Jaden
# get notified on NotBounties Updates
update-notification: true
# allow a npc to claim a bounty
npc-claim: false
# limit bounties to a max number of setters - other players can't set a bounty on a player if the maximum has been hit - (-1) to disable
max-setters: -1
# prompt the player with the confirm-bounty gui before they set a bounty
confirmation: true
# The name of bounties set by console. The murder bounties will also use this name
console-bounty-name: Sheriff
# this will remove bounties of banned players - checks are run every 12 hours
remove-banned-players: true
# allow players on the same team claim each-other's bounties
teams:
  # claim if on the same scoreboard team
  scoreboard-claim: false
  # players with the same placeholder result will not be able to claim each other's bounties (Must have PlaceholderAPI installed)
  # ex: '%luckperms_prefix%' would prevent anyone with the same prefix from killing each other
  placeholder: ''
  # claim if on the same BetterTeams team (Must have BetterTeams installed)
  bt-claim: false
  # claim if allied with each other's BetterTeams team
  bt-allies: false
# auto-updating bounty poster board
bounty-board:
  # 0 oldest bounties
  # 1 newest bounties
  # 2 top bounties
  # 3 lowest bounties
  type: 2
  # how many seconds between the board updates - minimum of 2 seconds (this can be server intensive)
  update-interval: 5
  # amount of bounty boards to update at a time - 0 to disable
  staggered-update: 3
  # glow item frame
  glow: true
  # invisible item frame
  invisible: true
# add a tag above a player's head if they have a bounty
wanted-tag:
  enabled: true
  # how high above the player's eyes the tag is
  offset: 0.4
  # text above the player
  text: '&f{level}&6&lWANTED&f: {amount}'
  # minimum bounty to display tag
  min-bounty: 100
  # hide the tag when sneaking
  hide-when-sneaking: true
  # text for certain levels of bounty
  level:
    # minimum bounty amount: text
    1000: '&f☠ '
    2500: '&c☠☠ '
    5000: '&4☠☠☠ '
# commands to be executed when a bounty is claimed
  # {player} is replaced with the person whose bounty was claimed
  # {killer} is replaced with the person who claimed the bounty
  # starting with [player] will run the command for the person whose bounty was claimed
  # starting with [killer] will run the command for the person who claimed the bounty
  # starting with nothing will run the command as console
  # using [sound_player] (SOUND_ID) <VOLUME> <PITCH> will play a sound for the player
  # using [sound_killer] (SOUND_ID) <VOLUME> <PITCH> will play a sound for the killer
  # using [sound] (SOUND_ID) <VOLUME> <PITCH> will play a sound for everyone near the death
  # The volume and pitch are optional. Sound IDs can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  # adding @(player/killer)permission or !@(player/killer)permission before everything with check for a permission of the player or killer to run the command
  # This will check if the killer has the permission and will message the person they killed
  # ex: @(killer)notbounties.view [killer] msg {player} It wasn''t personal.
  # a command that is just <respawn> will force the player to respawn. This is useful if you want to tp them somewhere after they die
  # You can use placeholders, but they will always be parsed for the player who died
bounty-claim-commands: []
# add a bounty if a player kills another player
murder-bounty:
  # How many seconds before you can kill the same person and increase your bounty
  player-cooldown: 360
  # how much the bounty increases per player kill. Consider raising minimum-broadcast if you change this if you don't want a message in chat
  bounty-increase: 10
  # you will be excluded from the bounty increase if you are claiming another bounty
  exclude-claiming: true
# set a random bounty every once in a while
random-bounties:
  # minimum seconds between next random bounty - 0 to disable
  min-time: 0 # 86400 seconds in a day
  # maximum seconds between next random bounty
  max-time: 0
  # minimum bounty price
  min-price: 10
  # maximum bounty price
  max-price: 100
# wanted posters of bounty
bounty-posters:
  # players can give themselves bounty posters of any bounty, otherwise, only admins can give posters
  give-own: false
  # display bounty reward on the poster
  # note: changing this will change the position of the names and can cause text to overlap
  #       if you want to change this, I suggest setting clean-posters to true
  display-reward: true
  # reward text below name if display-reward is enabled
  # placeholders can be used here
  reward-text: 'REWARD: {reward}'
  # lock the bounty map - this will improve performance, but the maps will not update after they are created
  # if you turn this on, I advise disabling display-reward to avoid confusing your players
  lock-maps: false
  # true adds the currency prefix and suffix to the reward text
  # Some special characters like ◆ do not work on the poster
  currency-wrap: false
  # The line right below the player head
  # placeholders can be used in here, but will only get updated every server restart if save-templates is false
  # Long text here may make the names illegible
  name-line: '{name}'
  # how many milliseconds between map updates
  update-interval: 2000
  # always update the map even if the bounty hasn't changed
  always-update: false
  # save created maps to be used later - player heads will not change unless the player changes their name
  save-templates: true
  # delete all the saved poster templates in the NotBounties/posters folder
  # set this to true if you change anything about what is displayed on the poster besides reward-text and currency-wrap
  # this will be set to false again automatically after a clean has been done
  clean-posters: false
# filter on where bounties can be claimed
world-filter:
  # true to whitelist the list of worlds
  # false to blacklist the list of worlds
  whitelist: false
  # world names to whitelist or blacklist
  worlds:
    - SafeWorld
bounty-whitelist:
  # allow players to whitelist other players to claim bounties they set
  enabled: true
  # cost to add 1 player to the bounty whitelist - up to 10 players can be added
  cost: 10
  # show everyone bounties that are not whitelisted to them
  show-all-bounty: false
  # allow players to change their whitelist for bounties that have already been set
  # I suggest setting cost to 0 if you are doing this
  variable-whitelist: false
  # Allows players to change their whitelist into a blacklist
  enable-blacklist: true
reward-heads:
  # give player heads to the setter of the bounty once claimed
  setters: true
  # give player head of victim to the killer once claimed
  claimed: false
# this will give players a piece of paper after claiming a bounty that can be right-clicked to redeem the reward
redeem-reward-later: false
# players can buy their own bounties for an increased amount - uses remove-currency-commands
buy-own-bounties:
  enabled: true
  # bounty set for $100 would have to be bought for $125
  cost-multiply: 1.25
immunity:
  # players can buy immunity from having bounties set on them as opposed to having immunity from the permission node notbounties.immune
  # Immunity types:
  # 0 - disabled
  # 1 - permanent immunity
  # 2 - scaling immunity
  # 3 - time immunity
  type: 2
  # immunity will never run out
  permanent-immunity:
    cost: 128
  # immunity will be stronger the more money you spend - only if permanent immunity is disabled
  # if you buy immunity for 2500, then it protects you from bounties set for 2500, 2499, 1500, etc. (with ratio set to 1)
  # bounties can be set on you for 2501 and higher
  scaling-immunity:
    # money spent -> bounty protection
    # ex: if ratio is 0.5, buying immunity for 1000 will protect you from bounties 500 or less
    ratio: 1.0
  # immunity wil only last for a period of time
  time-immunity:
    # how many seconds 1 currency will add to your immunity
    # ex: spending $15 with seconds: 3600 will give you 54000 seconds of immunity, or 15 hours
    seconds: 3600
  # in SECONDS how long before a player can set a bounty on a player that was just killed with a bounty
  grace-period: 10
# give players with big bounties perks
big-bounties:
  # how big their bounty must be for the effects to take place
  # set -1 to disable
  bounty-threshold: 25000
  # whether a soul fire flame will be above the player's head
  particle: true
  # commands to be executed when the player reaches a bounty over the threshold
  commands:
    - 'execute run effect give {player} minecraft:glowing 10 0'
# special compass allows you to track people with bounties
bounty-tracker:
  # whether the compasses will actually track a player
  # does not stop admins from getting new compasses, and they will still be removed
  enabled: true
  # whether players with notbounties.tracker can give themselves a tracker with the command
  give-own: false
  # When to remove the compass after the bounty has been claimed
  # the higher the number, the more performance heavy it will be on your server
  # 0 - don't ever remove it
  # 1 - remove it if they try to hold it
  # 2 - check inventories every 5 minutes
  # 3 - check inventory every time player opens a container
  remove: 2
  # how many blocks away until it the player starts glowing - 0 to disable
  # this is also how many blocks away until the tracked player gets a message about being tracked
  glow: 10
  # information to show when a player is holding a tracker
  action-bar:
    enabled: true
    # always show when holding - false only shows when they right-click
    show-always: true
    # show the name of the player who you are tracking
    player-name: true
    # show the distance in meters away from your target
    distance: true
    # show x y z of your target
    position: false
    # show the world of your target
    world: false
    # with everything enabled it would look something like:
    # Not_Jaden - 25m - 13x 63y 20z - world
# MySQL connection - you don't have to change anything if you don't want to use it
database:
  host: localhost
  port: 3306
  database: db
  user: username
  password: pass
  use-ssl: false
  # automatically move data stored locally to the MySQL database when one connects
  migrate-local-data: true
  # automatically try to connect to the database if a connection was lost
  auto-connect: false