# config.yml
# Miscellaneous configuration settings.
# The main configuration that people do is setting up the currency in the settings/money.yml file. (or do /bounty currency)
# Wiki: https://github.com/No-Not-Jaden/NotBounties/wiki

# make old bounties expire after a while
bounty-expire:
  # how many real days until bounties expire | -1 to disable
  # the lowest this can go is around 0.00346 (5 minutes). Expired bounties are checked every 5 minutes.
  # check auto-bounties for their expiry time
  time: -1
  # track the player while they are offline
  offline-tracking: true
  # give the bounty amount to the receiver if it expires. false means that the setter gets the refund.
  # if you change this, change the expired-bounty message in language.yml because it won't be accurate anymore
  reward-receiver: false

# These player's bounty stats will be hidden from bounties top
hide-stats:
  - Not_Jaden
# get notified on NotBounties Updates
update-notification: true
# allow a npc to claim a bounty
npc-claim: false
# allow players with the same ip address to claim bounties on each other
same-ip-claim: true
# limit bounties to a max number of setters - other players can't set a bounty on a player if the maximum has been hit - (-1) to disable
max-setters: -1
# allow players to set bounties on people who are offline
offline-set: true
# prompt the player with the confirm-bounty gui before they set a bounty
confirmation: true
# this will remove bounties of banned players - checks are run every 12 hours
remove-banned-players: true
# allow players to set bounties on themselves
self-setting: true
# Allow players with bounties to get their own reward by killing the players who set a bounty on them
steal-bounties: false
# Change the order when the bounties are claimed event wise
# BEFORE, REGULAR, or AFTER can be used
# do not change this unless you know what you are doing
claim-order: REGULAR
# automatically display times in the timezone of each player
auto-timezone: true
# reduce the number of players that are stored when using the GUI
# you cannot use the {max_page} placeholder if this is true
reduce-page-calculations: true
# An extra check to make sure the player is visible to see them in the player selection
see-player-list: false
# The maximum amount of logged players until tab-complete no longer fills offline players. A lower number improves tab-complete performance
max-tab-complete-players: 50
# How often player data will be saved in minutes.
auto-save-interval: 15
# back up any locally stored data
bounty-backups: true
# How long a player has to wait before setting another bounty - measured in seconds
bounty-cooldown: 2

# The commands players can use to use bounties.
# The first option is the one the plugin uses when forcing players to execute a command.
# A restart is required after making changes.
# Make sure another plugin doesn't override these.
plugin-bounty-commands:
  - 'notbounties'
  - 'bounty'

# restrict PVP
pvp-restrictions:
  # worlds to restrict PVP
  # set to the following if you want it to apply to all worlds
  #worlds: []
  worlds:
    - pvp_restriction_world
  # pvp rules
  # 0 - only combat logging is used
  # 1 - players can only damage other players with bounties
  # 2 - players can damage other players with bounties and those players can fight back
  # 3 - players can damage other players with bounties and players with bounties can damage anyone
  rule: 2
  # if rule is set to 2 - the time in seconds that players with bounties can fight back after taking damage from another player
  pvp-time: 60
  # claim bounties if players combat-log
  combat-logging:
    # time in seconds that a player must be without combat to log out without losing their bounty - 0 to disable
    time: 0
    # send the combat-tag and combat-safe messages when they are tagged
    send-message: false
    # override the death tax for this combat log
    # -1 to disable
    death-tax-override: -1

# What happens when a player clicks a bounty in the GUI
bounty-gui-clicks:
  # Available Actions:
  # POSTER   - give a bounty poster (give-own must be enabled in bounty-posters section)
  # TRACKER  - give a bounty tracker, or write to a tracker (one of those options must be enabled in bounty-trackers section)
  # VIEW     - opens the view-bounty GUI
  # REMOVE   - remove a bounty (must have notbounties.admin to execute)
  # EDIT     - edit a bounty (must have notbounties.admin to execute)
  # NONE     - no action on this click
  # If you change this, you might want to change the following text in language.yml:
  # give-tracker-lore, give-poster-lore, view-bounty-lore, remove-bounty-lore, and edit-bounty-lore
  right: POSTER
  left: TRACKER # Left click will be overridden on your own bounty to buy it back if buy-own-bounties is enabled
  middle: NONE # Middle clicks only work when in creative
  drop: VIEW
  bedrock: VIEW # If using a simple GUI, bedrock players have only 1 click option
  # These options override the click actions above if you have the notbounties.admin permission
  admin:
    right: EDIT
    left: REMOVE
    middle: NONE
    drop: VIEW
    bedrock: VIEW

# filter on where bounties can be claimed
world-filter:
  # true to whitelist the list of worlds
  # false to blacklist the list of worlds
  whitelist: false
  # world names to whitelist or blacklist
  worlds:
    - SafeWorld

bounty-whitelist:
  # allow players to whitelist other players to claim bounties they set
  enabled: false
  # cost to add 1 player to the bounty whitelist - up to 10 players can be added
  cost: 10
  # show everyone bounties that are not whitelisted to them
  show-all-bounty: false
  # allow players to change their whitelist for bounties that have already been set
  # I suggest setting cost to 0 if you are doing this
  variable-whitelist: false
  # Allows players to change their whitelist into a blacklist
  enable-blacklist: true

reward-heads:
  # give player heads to the setter of the bounty once claimed
  setters: true
  # give player head of victim to the killer once claimed
  claimed: false
  # drop player head when anyone is killed
  any-kill: false

# send server stats like most other plugins do
send-bstats: true