name: NotBounties
version: '${project.version}'
main: me.jadenp.notbounties.NotBounties
api-version: 1.13
authors: [ Not_Jaden ]
description: kill...
softdepend:
  - PlaceholderAPI
  - HeadDataBase
  - Vault
  - LiteBans
  - SkinsRestorer
  - BetterTeams
  - Towny
  - Geyser-Spigot
  - floodgate
  - Kingdoms
  - Lands
  - WorldGuard
commands:
  notbounties:
    aliases:
      - notbounty
      - nbounty
      - bounty
      - nbounties
      - bounties
    description: Set and check bounties.
permissions:
  notbounties.admin:
    default: op
    description: Remove or edit bounties.
  notbounties.set:
    default: true
    description: Set bounties.
  notbounties.view:
    default: true
    description: View bounties and the bounty GUI.
  notbounties.buyown:
    default: true
    description: Buy your own bounty.
  notbounties.immune:
    default: false
    description: Immune to having bounties set on them.
  notbounties.buyimmunity:
    default: true
    description: Buy immunity.
  notbounties.removeimmunity:
    default: false
    description: Remove own immunity.
  notbounties.tracker:
    default: true
    description: Use a bounty tracker.
  notbounties.whitelist:
    default: true
    description: Whitelist players to claim your bounty.
  notbounties.basic:
    default: true
    description: Use help, tutorial, and broadcast commands.
  notbounties.removeset:
    default: false
    description: Remove bounties you set.
  notbounties.player:
    description: All the basic player permissions.
    children:
      - notbounties.set
      - notbounties.view
      - notbounties.buyown
      - notbounties.buyimmunity
      - notbounties.removeimmunity
      - notbounties.tracker
      - notbounties.whitelist
      - notbounties.basic
  notbounties.immunity.murder:
    default: false
    description: Immune to murder auto-bounties.
  notbounties.immunity.random:
    default: false
    description: Immune to random auto-bounties.
  notbounties.immunity.timed:
    default: false
    description: Immune to timed auto-bounties.